### ISSUE TITLE
The fonts aren't Anton

### ISSUE THREAD

**Issue by katiesteckles** [christianp/mathsjam-site#9]
Why aren't all the fonts Anton?

**Comment by christianp** [comment]
Or maybe [Fjalla One](https://fonts.google.com/specimen/Fjalla+One)

**Comment by katiesteckles** [comment]
Yes! That's perfect. good work!

**Comment by christianp** [comment]
It now looks like this:
![image](https://cloud.githubusercontent.com/assets/19513/22929003/2fa3de3a-f2b1-11e6-8d9c-a13d6637d375.png)
I think it's quite good! What do you think about the body font? I went with a sans-serif font originally because I wanted it to look a bit like a pub menu, but maybe something else would be better now the heading font has changed.

**Comment by katiesteckles** [comment]
Serif is meant to be easier to read for longer passages, and sans for
headings; I don't mind, but maybe a sans font that goes with it might look
better in this setup.

**Comment by christianp** [comment]
I've changed it to Merriweather, which is a more readable serif. Merriweather Sans didn't look very good.

![image](https://cloud.githubusercontent.com/assets/19513/22930497/802083a2-f2b8-11e6-88e3-76c0c794f0f7.png)
